In [2]:
#from satellite_analysis.catalogreaders import conistentcatalogreader as consistent
from satellite_analysis.catalogreaders import consistentcatalogreader as consistent

input_dir = '/Users/user1/documents/GEN3/rockstar_moresnaps/VELA08/hlists'

consistent.consistent_catalog_reader(input_dir, remove_subhalos='False')

Consistent File Indices: ['099', '100', '102', '104', '107', '110', '112', '115', '117', '120', '122', '124', '127', '129', '130', '132', '134', '137', '140', '142', '144', '147', '150', '152', '155', '157', '160', '162', '165', '167', '170', '172', '175', '177', '179', '180', '182', '184', '187', '190', '192', '194', '197', '200', '202', '204', '207', '210', '212', '214', '217', '219', '220', '222', '224', '227', '229', '230', '232', '234', '237', '240', '242', '245', '247', '250', '252', '255', '257', '259', '260', '262', '265', '267', '269', '270', '272', '274', '277', '280', '281', '285', '287', '290', '292', '294', '297', '299', '300', '302', '305', '307', '310', '312', '315', '317', '320', '322', '325', '327', '329', '330', '332', '335', '337', '340', '342', '345', '347', '350', '352', '355', '357', '360', '362', '364', '367', '370', '372', '375', '377', '380', '382', '385', '387', '390', '392', '394', '397', '400', '402', '405', '407', '409', '410', '412', '413', '417', '420', '422', '424', '427', '429', '430', '432', '434', '437', '440', '442', '444', '447', '449', '450', '452', '454', '457', '460', '462', '465', '467', '470', '472', '475', '477', '479', '480', '482', '484', '487', '489', '490', '491', '495', '497', '500', '502', '505', '507', '510', '512', '514', '517', '519', '520', '522', '525', '527', '528', '530', '532', '535', '537', '540', '542', '545', '547', '549', '550', '551', '552', '555', '557', '559', '560', '570']

Using Indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204]

Number of Halos found for snapshot 0 : 71
Number of Halos found for snapshot 1 : 71
Number of Halos found for snapshot 2 : 83
Number of Halos found for snapshot 3 : 98
Number of Halos found for snapshot 4 : 108
Number of Halos found for snapshot 5 : 129
Number of Halos found for snapshot 6 : 142
Number of Halos found for snapshot 7 : 160
Number of Halos found for snapshot 8 : 175
Number of Halos found for snapshot 9 : 198
Number of Halos found for snapshot 10 : 203
Number of Halos found for snapshot 11 : 219
Number of Halos found for snapshot 12 : 245
Number of Halos found for snapshot 13 : 261
Number of Halos found for snapshot 14 : 265
Number of Halos found for snapshot 15 : 283
Number of Halos found for snapshot 16 : 294
Number of Halos found for snapshot 17 : 299
Number of Halos found for snapshot 18 : 314
Number of Halos found for snapshot 19 : 328
Number of Halos found for snapshot 20 : 335
Number of Halos found for snapshot 21 : 345
Number of Halos found for snapshot 22 : 358
Number of Halos found for snapshot 23 : 366
Number of Halos found for snapshot 24 : 384
Number of Halos found for snapshot 25 : 389
Number of Halos found for snapshot 26 : 406
Number of Halos found for snapshot 27 : 414
Number of Halos found for snapshot 28 : 428
Number of Halos found for snapshot 29 : 435
Number of Halos found for snapshot 30 : 434
Number of Halos found for snapshot 31 : 448
Number of Halos found for snapshot 32 : 456
Number of Halos found for snapshot 33 : 467
Number of Halos found for snapshot 34 : 474
Number of Halos found for snapshot 35 : 472
Number of Halos found for snapshot 36 : 483
Number of Halos found for snapshot 37 : 484
Number of Halos found for snapshot 38 : 487
Number of Halos found for snapshot 39 : 500
Number of Halos found for snapshot 40 : 496
Number of Halos found for snapshot 41 : 504
Number of Halos found for snapshot 42 : 511
Number of Halos found for snapshot 43 : 512
Number of Halos found for snapshot 44 : 518
Number of Halos found for snapshot 45 : 516
Number of Halos found for snapshot 46 : 517
Number of Halos found for snapshot 47 : 525
Number of Halos found for snapshot 48 : 525
Number of Halos found for snapshot 49 : 527
Number of Halos found for snapshot 50 : 527
Number of Halos found for snapshot 51 : 534
Number of Halos found for snapshot 52 : 530
Number of Halos found for snapshot 53 : 530
Number of Halos found for snapshot 54 : 526
Number of Halos found for snapshot 55 : 534
Number of Halos found for snapshot 56 : 530
Number of Halos found for snapshot 57 : 535
Number of Halos found for snapshot 58 : 528
Number of Halos found for snapshot 59 : 529
Number of Halos found for snapshot 60 : 522
Number of Halos found for snapshot 61 : 528
Number of Halos found for snapshot 62 : 523
Number of Halos found for snapshot 63 : 527
Number of Halos found for snapshot 64 : 528
Number of Halos found for snapshot 65 : 525
Number of Halos found for snapshot 66 : 528
Number of Halos found for snapshot 67 : 527
Number of Halos found for snapshot 68 : 529
Number of Halos found for snapshot 69 : 532
Number of Halos found for snapshot 70 : 529
Number of Halos found for snapshot 71 : 533
Number of Halos found for snapshot 72 : 531
Number of Halos found for snapshot 73 : 533
Number of Halos found for snapshot 74 : 526
Number of Halos found for snapshot 75 : 527
Number of Halos found for snapshot 76 : 528
Number of Halos found for snapshot 77 : 526
Number of Halos found for snapshot 78 : 518
Number of Halos found for snapshot 79 : 518
Number of Halos found for snapshot 80 : 517
Number of Halos found for snapshot 81 : 513
Number of Halos found for snapshot 82 : 510
Number of Halos found for snapshot 83 : 506
Number of Halos found for snapshot 84 : 514
Number of Halos found for snapshot 85 : 512
Number of Halos found for snapshot 86 : 509
Number of Halos found for snapshot 87 : 507
Number of Halos found for snapshot 88 : 507
Number of Halos found for snapshot 89 : 507
Number of Halos found for snapshot 90 : 500
Number of Halos found for snapshot 91 : 499
Number of Halos found for snapshot 92 : 503
Number of Halos found for snapshot 93 : 503
Number of Halos found for snapshot 94 : 494
Number of Halos found for snapshot 95 : 491
Number of Halos found for snapshot 96 : 484
Number of Halos found for snapshot 97 : 484
Number of Halos found for snapshot 98 : 481
Number of Halos found for snapshot 99 : 474
Number of Halos found for snapshot 100 : 477
Number of Halos found for snapshot 101 : 479
Number of Halos found for snapshot 102 : 479
Number of Halos found for snapshot 103 : 473
Number of Halos found for snapshot 104 : 470
Number of Halos found for snapshot 105 : 938
Number of Halos found for snapshot 106 : 469
Number of Halos found for snapshot 107 : 466
Number of Halos found for snapshot 108 : 465
Number of Halos found for snapshot 109 : 463
Number of Halos found for snapshot 110 : 463
Number of Halos found for snapshot 111 : 459
Number of Halos found for snapshot 112 : 456
Number of Halos found for snapshot 113 : 450
Number of Halos found for snapshot 114 : 443
Number of Halos found for snapshot 115 : 443
Number of Halos found for snapshot 116 : 442
Number of Halos found for snapshot 117 : 443
Number of Halos found for snapshot 118 : 443
Number of Halos found for snapshot 119 : 440
Number of Halos found for snapshot 120 : 437
Number of Halos found for snapshot 121 : 434
Number of Halos found for snapshot 122 : 428
Number of Halos found for snapshot 123 : 428
Number of Halos found for snapshot 124 : 423
Number of Halos found for snapshot 125 : 428
Number of Halos found for snapshot 126 : 425
Number of Halos found for snapshot 127 : 419
Number of Halos found for snapshot 128 : 424
Number of Halos found for snapshot 129 : 420
Number of Halos found for snapshot 130 : 415
Number of Halos found for snapshot 131 : 413

Number of Halos found for snapshot 132 : 414
Number of Halos found for snapshot 133 : 416
Number of Halos found for snapshot 134 : 414
Number of Halos found for snapshot 135 : 414
Number of Halos found for snapshot 136 : 410
Number of Halos found for snapshot 137 : 411
Number of Halos found for snapshot 138 : 409
Number of Halos found for snapshot 139 : 406
Number of Halos found for snapshot 140 : 402
Number of Halos found for snapshot 141 : 396
Number of Halos found for snapshot 142 : 396
Number of Halos found for snapshot 143 : 396
Number of Halos found for snapshot 144 : 394
Number of Halos found for snapshot 145 : 393
Number of Halos found for snapshot 146 : 396
Number of Halos found for snapshot 147 : 393
Number of Halos found for snapshot 148 : 388
Number of Halos found for snapshot 149 : 386
Number of Halos found for snapshot 150 : 386
Number of Halos found for snapshot 151 : 388
Number of Halos found for snapshot 152 : 385
Number of Halos found for snapshot 153 : 383
Number of Halos found for snapshot 154 : 380
Number of Halos found for snapshot 155 : 379
Number of Halos found for snapshot 156 : 376
Number of Halos found for snapshot 157 : 375
Number of Halos found for snapshot 158 : 372
Number of Halos found for snapshot 159 : 366
Number of Halos found for snapshot 160 : 365
Number of Halos found for snapshot 161 : 360
Number of Halos found for snapshot 162 : 359
Number of Halos found for snapshot 163 : 355
Number of Halos found for snapshot 164 : 353
Number of Halos found for snapshot 165 : 356
Number of Halos found for snapshot 166 : 355
Number of Halos found for snapshot 167 : 352
Number of Halos found for snapshot 168 : 348
Number of Halos found for snapshot 169 : 345
Number of Halos found for snapshot 170 : 345
Number of Halos found for snapshot 171 : 344
Number of Halos found for snapshot 172 : 338
Number of Halos found for snapshot 173 : 337
Number of Halos found for snapshot 174 : 337
Number of Halos found for snapshot 175 : 335
Number of Halos found for snapshot 176 : 331
Number of Halos found for snapshot 177 : 328
Number of Halos found for snapshot 178 : 327
Number of Halos found for snapshot 179 : 326
Number of Halos found for snapshot 180 : 327
Number of Halos found for snapshot 181 : 326
Number of Halos found for snapshot 182 : 324
Number of Halos found for snapshot 183 : 323
Number of Halos found for snapshot 184 : 324
Number of Halos found for snapshot 185 : 321
Number of Halos found for snapshot 186 : 316
Number of Halos found for snapshot 187 : 314
Number of Halos found for snapshot 188 : 309
Number of Halos found for snapshot 189 : 306
Number of Halos found for snapshot 190 : 302
Number of Halos found for snapshot 191 : 303
Number of Halos found for snapshot 192 : 301
Number of Halos found for snapshot 193 : 298
Number of Halos found for snapshot 194 : 295
Number of Halos found for snapshot 195 : 293
Number of Halos found for snapshot 196 : 291
Number of Halos found for snapshot 197 : 291
Number of Halos found for snapshot 198 : 289
Number of Halos found for snapshot 199 : 287
Number of Halos found for snapshot 200 : 285
Number of Halos found for snapshot 201 : 286
Number of Halos found for snapshot 202 : 286
Number of Halos found for snapshot 203 : 284
Number of Halos found for snapshot 204 : 281

In [3]:
print(consistent.consistent_file_index[107])

345

In [10]:
count = 0
for item in consistent.halo_data_sorted[80][0]:
    print(count, item)
    count = count + 1

0 0.27737
1 2550293
2 0.28013
3 2571817
4 83
5 -1
6 -1
7 -1
8 0
9 4.38100e+11
10 4.38000e+11
11 196.812000
12 32.473000
13 255.700000
14 1
15 0.20767
16 203.770000
17 19.89874
18 18.65030
19 21.19371
20 -10.500
21 121.980
22 -66.220
23 -2.017e+11
24 3.143e+09
25 -1.084e+11
26 0.02028
27 184534
28 118
29 4178708
30 1401
31 80
32 281239
33 281238
34 198
35 0.00000
36 -1
37 31.8439
38 442330000000
39 430670000000
40 425700000000
41 305070000000
42 152090000000
43 24.4912
44 32.08
45 0.03645
46 0.83909
47 0.69924
48 -0.43205
49 -3.81701
50 3.93678
51 0.79606
52 0.72854
53 0.67418
54 3.22371
55 -3.03678
56 0.8597
57 368100000000
58 322700000000
59 85.687
60 4.38000e+11
61 4.38000e+11
62 203.770000
63 213.950000
64 0.22473
65 2.854e+02
66 2.750e+02
67 2.761e+02
68 3.675e+02
69 2.961e+02
70 6.567e-11
71 1.812e-11
72 0.27737
73 0.27737
74 0.27737
75 4.380e+11
76 203.770
77 203.770
78 0.00000
79 0.00744
80 -1.00000
81 2550293

In [2]:
import glob
import mysql.connector

from mysql.connector import (connection)

ones_wrong = []

#now we create the table in the database we want to add

mydb = connection.MySQLConnection(user='root', password='password',
                                 host='127.0.0.1', database='VELA_GEN3')

#print(mydb)

cursor = mydb.cursor()

#(VELA_number, scale_factor, scale, rockstar_id, desc_scale, desc_id, num_prog, pid, upid, desc_pid, phantom, sam_Mvir, Mvir, Rvir, rs, vrms, mmp?, scale_of_last_MM, vmax, x, y, z, vx, vy, vz, Jx, Jy, Jz, Spin, Breadth_first_ID, Depth_first_ID, Tree_root_ID, Orig_halo_ID, Snap_idx, Next_coprogenitor_depthfirst_ID, Last_progenitor_depthfirst_ID, Last_mainleaf_depthfirst_ID, Tidal_Force, Tidal_ID, Rs_Klypin, Mvir_all, M200b, M200c, M500c, M2500c, Xoff, Voff, Spin_Bullock, b_to_a, c_to_a, A_x, A_y, A_z, b_to_a_500c, c_to_a_500c, A_x_500c, A_y_500c, A_z_500c, T_over_U, M_pe_Behroozi, M_pe_Diemer, Halfmass_Radius, Macc, Mpeak, Vacc, Vpeak, Halfmass_Scale, Acc_Rate_Inst, Acc_Rate_100Myr, Acc_Rate_1_Tdyn, Acc_Rate_2_Tdyn, Acc_Rate_Mpeak, Acc_Log_Vmax_Inst, Acc_Log_Vmax_1_Tdyn, Mpeak_Scale, Acc_Scale, First_Acc_Scale, First_Acc_Mvir, First_Acc_Vmax, Vmax_at_Mpeak, Tidal_Force_Tdyn, Log_Vmax_Vmax_max_Tdyn;Tmpeak, Time_to_future_merger, Future_merger_MMP_ID)

#(VELA_number CHAR(2), scale_factor float(53), scale float(53), rockstar_id INT(255), desc_scale float(53), desc_id INT(255), num_prog INT(255), pid INT(255), upid INT(255), desc_pid INT(255), phantom INT(255), sam_Mvir float(53), Mvir float(53), Rvir float(53), rs float(53), vrms float(53), mmp? int(255), scale_of_last_MM float(53), vmax float(53), x float(53), y float(53), z float(53), vx float(53), vy float(53), vz float(53), Jx float(53), Jy float(53), Jz float(53), Spin float(53), Breadth_first_ID INT(255), Depth_first_ID INT(255), Tree_root_ID INT(255), Orig_halo_ID INT(255), Snap_idx INT(255), Next_coprogenitor_depthfirst_ID INT(255), Last_progenitor_depthfirst_ID INT(255), Last_mainleaf_depthfirst_ID INT(255), Tidal_Force float(53), Tidal_ID INT(255), Rs_Klypin float(53), Mvir_all BIGINT(255), M200b BIGINT(255), M200c BIGINT(255), M500c BIGINT(255), M2500c BIGINT(255), Xoff float(53), Voff float(53), Spin_Bullock float(53), b_to_a float(53), c_to_a float(53), A_x float(53), A_y float(53), A_z float(53), b_to_a_500c float(53), c_to_a_500c float(53), A_x_500c float(53), A_y_500c float(53), A_z_500c float(53), T_over_U float(53), M_pe_Behroozi BIGINT(255), M_pe_Diemer BIGINT(255), Halfmass_Radius float(53), Macc BIGINT(255), Mpeak BIGINT(255), Vacc float(53), Vpeak float(53), Halfmass_Scale float(53), Acc_Rate_Inst float(53), Acc_Rate_100Myr float(53), Acc_Rate_1_Tdyn float(53), Acc_Rate_2_Tdyn float(53), Acc_Rate_Mpeak float(53), Acc_Log_Vmax_Inst float(53), Acc_Log_Vmax_1_Tdyn float(53), Mpeak_Scale float(53), Acc_Scale float(53), First_Acc_Scale float(53), First_Acc_Mvir float(53), First_Acc_Vmax float(53), Vmax_at_Mpeak float(53), Tidal_Force_Tdyn float(53), Log_Vmax_Vmax_max_Tdyn;Tmpeak float(53), Time_to_future_merger float(53), Future_merger_MMP_ID INT(255))

#cursor.execute("CREATE TABLE rockstar (VELA_number CHAR(2), scale_factor float(53), scale float(53), rockstar_id INT(255), desc_scale float(53), desc_id INT(255), num_prog INT(255), pid INT(255), upid INT(255), desc_pid INT(255), phantom INT(255), sam_Mvir float(53), Mvir float(53), Rvir float(53), rs float(53), vrms float(53), mmp int(255), scale_of_last_MM float(53), vmax float(53), x float(53), y float(53), z float(53), vx float(53), vy float(53), vz float(53), Jx float(53), Jy float(53), Jz float(53), Spin float(53), Breadth_first_ID INT(255), Depth_first_ID INT(255), Tree_root_ID INT(255), Orig_halo_ID INT(255), Snap_idx INT(255), Next_coprogenitor_depthfirst_ID INT(255), Last_progenitor_depthfirst_ID INT(255), Last_mainleaf_depthfirst_ID INT(255), Tidal_Force float(53), Tidal_ID INT(255), Rs_Klypin float(53), Mvir_all float(53), M200b float(53), M200c float(53), M500c float(53), M2500c float(53), Xoff float(53), Voff float(53), Spin_Bullock float(53), b_to_a float(53), c_to_a float(53), A_x float(53), A_y float(53), A_z float(53), b_to_a_500c float(53), c_to_a_500c float(53), A_x_500c float(53), A_y_500c float(53), A_z_500c float(53), T_over_U float(53), M_pe_Behroozi float(53), M_pe_Diemer float(53), Halfmass_Radius float(53), Macc BIGINT(255), Mpeak BIGINT(255), Vacc float(53), Vpeak float(53), Halfmass_Scale float(53), Acc_Rate_Inst float(53), Acc_Rate_100Myr float(53), Acc_Rate_1_Tdyn float(53), Acc_Rate_2_Tdyn float(53), Acc_Rate_Mpeak float(53), Acc_Log_Vmax_Inst float(53), Acc_Log_Vmax_1_Tdyn float(53), Mpeak_Scale float(53), Acc_Scale float(53), First_Acc_Scale float(53), First_Acc_Mvir float(53), First_Acc_Vmax float(53), Vmax_at_Mpeak float(53), Tidal_Force_Tdyn float(53), Log_Vmax_Vmax_max_Tdyn_Tmpeak float(53), Time_to_future_merger float(53), Future_merger_MMP_ID INT(255))")


#now that the table is created, we read the data we want from each VELA sim file and load it into the table we just created

#VELA08 failed and VELA10 for same reason #also 15
VELA_numbers = ['07']

for VELA_number in VELA_numbers:
    print(VELA_number)
    rockstarfiles = glob.glob('/Users/user1/documents/GEN3/rockstar_moresnaps/VELA{}/hlists/hlist_*.list'.format(VELA_number))
    #print(rockstarfiles)
    

    for rockstarfile in rockstarfiles:
        values_to_add = []
        readfile = open(rockstarfile)
        lines = readfile.readlines()

        count = 0
        current_scale = float(rockstarfile[-10:-7])/1000
        for line in lines:
            #we want to skip the first line as it is just the headers
            if count <= 64:
                count = count + 1
                continue
            current_line = line.split()
            current_line_sql = [VELA_number, str(current_scale)] + [str(x) for x in current_line]
            values_to_add.append(tuple(current_line_sql))
        

        readfile.close()
        sql_add_command = 'INSERT INTO rockstar (VELA_number, scale_factor, scale, rockstar_id, desc_scale, desc_id, num_prog, pid, upid, desc_pid, phantom, sam_Mvir, Mvir, Rvir, rs, vrms, mmp, scale_of_last_MM, vmax, x, y, z, vx, vy, vz, Jx, Jy, Jz, Spin, Breadth_first_ID, Depth_first_ID, Tree_root_ID, Orig_halo_ID, Snap_idx, Next_coprogenitor_depthfirst_ID, Last_progenitor_depthfirst_ID, Last_mainleaf_depthfirst_ID, Tidal_Force, Tidal_ID, Rs_Klypin, Mvir_all, M200b, M200c, M500c, M2500c, Xoff, Voff, Spin_Bullock, b_to_a, c_to_a, A_x, A_y, A_z, b_to_a_500c, c_to_a_500c, A_x_500c, A_y_500c, A_z_500c, T_over_U, M_pe_Behroozi, M_pe_Diemer, Halfmass_Radius, Macc, Mpeak, Vacc, Vpeak, Halfmass_Scale, Acc_Rate_Inst, Acc_Rate_100Myr, Acc_Rate_1_Tdyn, Acc_Rate_2_Tdyn, Acc_Rate_Mpeak, Acc_Log_Vmax_Inst, Acc_Log_Vmax_1_Tdyn, Mpeak_Scale, Acc_Scale, First_Acc_Scale, First_Acc_Mvir, First_Acc_Vmax, Vmax_at_Mpeak, Tidal_Force_Tdyn, Log_Vmax_Vmax_max_Tdyn_Tmpeak, Time_to_future_merger, Future_merger_MMP_ID) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'
        cursor.executemany(sql_add_command, values_to_add)

        mydb.commit()

        print(cursor.rowcount, "was inserted.")
        
        #now check the values
        
        current_snap_rockstar = values_to_add[0][2]
        
        cursor.execute("SELECT * FROM rockstar HAVING VELA_number = {} AND scale = {}".format(VELA_number, current_snap_rockstar))

        myresult = cursor.fetchall()

        for x, y in zip(myresult, values_to_add):

            for x_sub, y_sub in zip(x,y):
                #this is for the rockstar_id, which are stored as a float with number.0 instead of number as they
                #are in the sql database, so to compare I have to make the ones from the ascii files ints
                if x_sub != int(float(y_sub)) and x_sub != float(y_sub) and x_sub != y_sub:
                    print(x_sub, y_sub)
                    print(type(x_sub), type(y_sub))
                    ones_wrong.append((VELA_number, current_scale, x_sub, y_sub))
    #print(values_to_add)   
    #now that we have the data we want to add, we add it to the Table
    #print(values_to_add[0])
    #sql_add_command = 'INSERT INTO rockstar (VELA_number, scale_factor, scale, rockstar_id, desc_scale, desc_id, num_prog, pid, upid, desc_pid, phantom, sam_Mvir, Mvir, Rvir, rs, vrms, mmp, scale_of_last_MM, vmax, x, y, z, vx, vy, vz, Jx, Jy, Jz, Spin, Breadth_first_ID, Depth_first_ID, Tree_root_ID, Orig_halo_ID, Snap_idx, Next_coprogenitor_depthfirst_ID, Last_progenitor_depthfirst_ID, Last_mainleaf_depthfirst_ID, Tidal_Force, Tidal_ID, Rs_Klypin, Mvir_all, M200b, M200c, M500c, M2500c, Xoff, Voff, Spin_Bullock, b_to_a, c_to_a, A_x, A_y, A_z, b_to_a_500c, c_to_a_500c, A_x_500c, A_y_500c, A_z_500c, T_over_U, M_pe_Behroozi, M_pe_Diemer, Halfmass_Radius, Macc, Mpeak, Vacc, Vpeak, Halfmass_Scale, Acc_Rate_Inst, Acc_Rate_100Myr, Acc_Rate_1_Tdyn, Acc_Rate_2_Tdyn, Acc_Rate_Mpeak, Acc_Log_Vmax_Inst, Acc_Log_Vmax_1_Tdyn, Mpeak_Scale, Acc_Scale, First_Acc_Scale, First_Acc_Mvir, First_Acc_Vmax, Vmax_at_Mpeak, Tidal_Force_Tdyn, Log_Vmax_Vmax_max_Tdyn_Tmpeak, Time_to_future_merger, Future_merger_MMP_ID) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'
    #cursor.executemany(sql_add_command, values_to_add)

    #mydb.commit()

    #print(cursor.rowcount, "was inserted.")
    
    #now we check that all the data matches and that no errors were made that need to be corrected
    
    
    #NEED TO CHANGE THIS TO ONLY GET ONES FROM VELA_Number
    
            
    print(VELA_number)
cursor.close()
mydb.close()

07
17189 was inserted.
17920 was inserted.
19906 was inserted.
21361 was inserted.
22471 was inserted.
23593 was inserted.
24334 was inserted.
24877 was inserted.
25266 was inserted.
25529 was inserted.
25791 was inserted.
26019 was inserted.
26182 was inserted.
26430 was inserted.
26148 was inserted.
26321 was inserted.
26516 was inserted.
26576 was inserted.
26673 was inserted.
26392 was inserted.
26314 was inserted.
26582 was inserted.
26528 was inserted.
26563 was inserted.
26435 was inserted.
26290 was inserted.
26239 was inserted.
26011 was inserted.
25692 was inserted.
25514 was inserted.
25411 was inserted.
25001 was inserted.
24730 was inserted.
24341 was inserted.
23994 was inserted.
23596 was inserted.
23321 was inserted.
22977 was inserted.
22719 was inserted.
22472 was inserted.
22184 was inserted.
21800 was inserted.
21466 was inserted.
21226 was inserted.
20935 was inserted.
20668 was inserted.
20378 was inserted.
20168 was inserted.
19918 was inserted.
19678 was inserted.
19344 was inserted.
19085 was inserted.
18827 was inserted.
18495 was inserted.
18185 was inserted.
17887 was inserted.
17568 was inserted.
17109 was inserted.
16806 was inserted.
16496 was inserted.
16224 was inserted.
16013 was inserted.
15832 was inserted.
15587 was inserted.
15344 was inserted.
15087 was inserted.
14859 was inserted.
14726 was inserted.
14512 was inserted.
14309 was inserted.
14194 was inserted.
14046 was inserted.
13899 was inserted.
13715 was inserted.
13557 was inserted.
13354 was inserted.
13229 was inserted.
13143 was inserted.
12997 was inserted.
12856 was inserted.
12714 was inserted.
12641 was inserted.
12488 was inserted.
12390 was inserted.
12270 was inserted.
12178 was inserted.
12115 was inserted.
12013 was inserted.
11906 was inserted.
11801 was inserted.
11702 was inserted.
11573 was inserted.
11472 was inserted.
11363 was inserted.
11269 was inserted.
11164 was inserted.
11098 was inserted.
11037 was inserted.
10957 was inserted.
10906 was inserted.
10818 was inserted.
10712 was inserted.
10627 was inserted.
10551 was inserted.
10475 was inserted.
10393 was inserted.
10302 was inserted.
10212 was inserted.
10145 was inserted.
10114 was inserted.
10045 was inserted.
9988 was inserted.
9919 was inserted.
9833 was inserted.
9755 was inserted.
9667 was inserted.
9598 was inserted.
9511 was inserted.
9450 was inserted.
9353 was inserted.
9254 was inserted.
9138 was inserted.
9048 was inserted.
8984 was inserted.
8900 was inserted.
8824 was inserted.
8736 was inserted.
8682 was inserted.
8630 was inserted.
8574 was inserted.
8526 was inserted.
8485 was inserted.
8424 was inserted.
8354 was inserted.
8284 was inserted.
8223 was inserted.
8166 was inserted.
8097 was inserted.
8029 was inserted.
7992 was inserted.
7940 was inserted.
7909 was inserted.
7858 was inserted.
7819 was inserted.
7782 was inserted.
7745 was inserted.
7724 was inserted.
7703 was inserted.
7676 was inserted.
7645 was inserted.
7633 was inserted.
7604 was inserted.
7585 was inserted.
7569 was inserted.
7537 was inserted.
7513 was inserted.
7491 was inserted.
7481 was inserted.
7444 was inserted.
7424 was inserted.
7410 was inserted.
7381 was inserted.
7358 was inserted.
7347 was inserted.
7333 was inserted.
7315 was inserted.
7303 was inserted.
7295 was inserted.
7270 was inserted.
7253 was inserted.
7236 was inserted.
7212 was inserted.
7194 was inserted.
7172 was inserted.
7162 was inserted.
7157 was inserted.
7160 was inserted.
7144 was inserted.
7143 was inserted.
7145 was inserted.
7133 was inserted.
7145 was inserted.
7143 was inserted.
7152 was inserted.
7146 was inserted.
7165 was inserted.
7178 was inserted.
7194 was inserted.
7221 was inserted.
7233 was inserted.
7255 was inserted.
7306 was inserted.
7319 was inserted.
7315 was inserted.
7286 was inserted.
7264 was inserted.
7232 was inserted.
7196 was inserted.
7141 was inserted.
07

In [25]:
cursor.close()
mydb.close()

In [11]:
print(ones_wrong[0])
print(ones_wrong[-1])

('15', 0.33, 0.33, '0.33058')
('15', 0.49, 1095705, '1099180')